// <auto-generated />
using BookLibrary.DataAccess.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookLibrary.DataAccess.SQLite.Migrations
{
    [DbContext(typeof(BookLibraryDbContext))]
    [Migration("20220225105416_InitilDatabase")]
    partial class InitilDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("BookLibrary.Business.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .HasColumnName("ISBN")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Book","BookSchema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Isbn = "101-11113502222",
                            Title = "Clean Code: Best Practices"
                        },
                        new
                        {
                            Id = 2,
                            Isbn = "101-22258489522",
                            Title = "Learn Design Patterns in R"
                        },
                        new
                        {
                            Id = 3,
                            Isbn = "131-33333889820",
                            Title = "A Red Apple Far From Tree"
                        },
                        new
                        {
                            Id = 4,
                            Isbn = "141-44444886529",
                            Title = "How to Fix Broken Chair"
                        },
                        new
                        {
                            Id = 5,
                            Isbn = "131-55554825527",
                            Title = "Do We Need Another One?"
                        },
                        new
                        {
                            Id = 6,
                            Isbn = "131-66684885431",
                            Title = "Hello World!"
                        },
                        new
                        {
                            Id = 7,
                            Isbn = "121-77784885431",
                            Title = "Java va JavaScript"
                        },
                        new
                        {
                            Id = 8,
                            Isbn = "101-88645218900",
                            Title = "WPF in C# v10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
