export const BORROWER_LIST_REQUEST = "BORROWER_LIST_REQUEST";
export const BORROWER_LIST_SUCCESS = "BORROWER_LIST_SUCCESS";
export const BORROWER_LIST_FAIL = "BORROWER_LIST_FAIL";
export const BORROWER_DETAILS_REQUEST = "BORROWER_DETAILS_REQUEST";
export const BORROWER_DETAILS_SUCCESS = "BORROWER_DETAILS_SUCCESS";
export const BORROWER_DETAILS_FAIL = "BORROWER_DETAILS_FAIL";
export const BORROWER_DETAILS_RESET = "BORROWER_DETAILS_RESET";
