export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_SELECT = "CATEGORY_SELECT";
export const CATEGORY_RESET = "CATEGORY_RESET";

export const ADD_FILTERS = "ADD_FILTERS";
export const RESET_FILTERS = "RESET_FILTERS";
